### ISSUE TITLE
Omnisharp Server and C# syntax highlighting does not happen when using UnityNova

### ISSUE THREAD

**Issue by frctlys** [AmigaAbattoir/CSharp.novaextension#1]
While the UnityNova application does work to open files in the Unity Engine as an External Editor, the Intellisense and syntax highlighting do not work.

This was tried with both the Autodetect Unity Project setting enabled and disabled.

**Comment by AmigaAbattoir** [comment]
Since I'm usually running the extension (as I'm developing), I may have not properly setup the code to have the extension launch when certain files like `*.cs` are opened. I'll look into it.

**Comment by AmigaAbattoir** [comment]
I just tried opening a C# file from a Unity project in Visual Studio Code. If I open just the file, it won't give me any code completion but I do get syntax highlighting. However, if I open the _folder_ containing the Unity project's *.csproj files in Visual Studio Code, it then does code completion. 

I just tried the same in Nova, and if I try opening the file by itself, I do not get the code completion either and I do get syntax highlighting like in VSCode. But if I open a project in Nova with the Unity project I do get code completion just like VSCode.

I changed this issue to "wontfix", since OmniSharp does requires a *.csproj or *.cake in order to properly handle completions. Opening a single file doesn't really do much, besides syntax highlighting and getting the symbols.

When using UnityNova, if you have a Nova project opened for that Unity project, then it will help Nova open up that file in that project's view and it will have issues and code completion.

I will be updating the README.md soon explaining this better.

I've thought about trying to go up a few folder to see if there's a *.csproj or *.sln file, but I'm not too sure that would be a good solution for this. Maybe having a little popup that notifies you that in order to get code completion, you need to use it with a Nova project might work better.

**Comment by frctlys** [comment]
Thank you so much for all of this info! Hope my reporting was helpful.

**Comment by AmigaAbattoir** [comment]
Marking as closed now that V0.4.3 is released. It should now show a message if you open the file outside of a project and warn you that it will not have all the features.
